### ISSUE TITLE
Pre-checkpoint cleanup

### ISSUE THREAD

**Issue by berkan-sahin** [cs102-project/LabConnect#15]
There are only a few hours left before the first checkpoint. We are (un)officially in a feature freeze and in a need to clean up the code prior to submission.

## TODO

- [x] Clean up inappropriate/unnecessary comments
- [x] Check variable naming
- [x] Summarize our progress
- [x] Write each member's contribution
- [x] Complete documentation
- [x] Merge `Models` to `master`
- [x] Make release `0.0.1`
- [x] Add a version w/ `readme.txt` as an artifact
- [x] Submit the code (the submitting member closes the issue)
