### ISSUE TITLE
Code Checkpoint 2

### ISSUE THREAD

**Issue by berkan-sahin** [cs102-project/LabConnect#17]
There are only a few hours left before the second checkpoint. We need to clean up and check the code prior to submission.

## TODO

- [x] Clean up inappropriate/unnecessary comments (and code!)
- [x] Check variable naming
- [x] Summarize our progress
- [x] Write each member's contribution
- [x] Complete documentation
- [x] Merge `checkpt-two` to `master`
- [x] Make release `0.0.2`
- [x] Add a version w/ `readme.txt` as an artifact
- [x] Submit the code (the submitting member closes the issue)
